### ISSUE TITLE
Indent incorrect if Heading contains #

### ISSUE THREAD

**Issue by frankmorgner** [raychenon/play-table-of-contents#22]
```md
# PKCS
# PKCS#11
```
is currently rendered as
```md
**[Table of Contents](http://tableofcontent.eu)**
<!-- Table of contents generated generated by http://tableofcontent.eu -->
- [PKCS](#pkcs)
  - [PKCS#11](#pkcs11)
```
but it should have been
```md
**[Table of Contents](http://tableofcontent.eu)**
<!-- Table of contents generated generated by http://tableofcontent.eu -->
- [PKCS](#pkcs)
- [PKCS#11](#pkcs11)
```
Escaping the hashtag leads to the same result...

**Comment by raychenon** [comment]
Thanks Frank, I know where to [fix this](https://github.com/raychenon/play-table-of-contents/blob/master/app/readme/TableOfContentHelper.scala#L50).  Only the subsequent # should be counted.

The fix can be pushed tomorrow evening. Sorry I'm having something planned tonight.

**Comment by frankmorgner** [comment]
thanks! https://tableofcontents.herokuapp.com/ seems to currently have an issue, though.

**Comment by raychenon** [comment]
Let's re-open this , since https://tableofcontents.herokuapp.com/  has an issue.
I see the build succeeded, I'll see tonight. The heroku CLI  is installed on my personal Mac.

**Comment by frankmorgner** [comment]
Great, thanks!
