### ISSUE TITLE
Better slugification

### ISSUE THREAD

**Issue by julien-f** [raychenon/play-table-of-contents#4]
Link are incorrect with special chars, examples:

- `promises::all([ mapper ])` → `#promisesall-mapper-` (~~`#promises::all([-mapper-])`~~)
- `join(p1, ..., pn, cb) / join([p1, ..., pn], cb)` → `#joinp1--pn-cb--joinp1--pn-cb` (~~`#join(p1,-...,-pn,-cb)-/-join([p1,-...,-pn],-cb)`~~)

**Comment by raychenon** [comment]
So what chars should be accepted ? only numbers and letters [1-9,a-z,A-Z]

**Comment by raychenon** [comment]
Salut @julien-f ,

the code is published.

- `promises::all([ mapper ])` → `#promisesall-mapper` wrong : (`#promisesall-mapper-`) **no need of - at the end**
- `join(p1, ..., pn, cb) / join([p1, ..., pn], cb)` → `#joinp1-pn-cb-joinp1-pn-cb` wrong : (`#joinp1--pn-cb--joinp1--pn-cb`)  **no need for double --**

Re-open the ticket if you think if there is something wrong.
